In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('foo-page-2-table-1.csv')

In [118]:
df_districts = pd.read_csv('foo-page-2-table-1.csv')
# incase HR extraction not correct rename the table name and use this
# df_districts = pd.read_csv('../INPUT/{}/{}/foo-page-2-table-1_editTable.csv'.format(date,StateCode))
# print('HR districts data:',df_districts)

df_districts.columns = df_districts.columns.str.replace("\n","")

# print(df_districts.columns)
# df_districts["Name of District"] = df_districts['Sr No'] + df_districts['Name of District']

# # df_tests = pd.read_csv('../INPUT/{}/{}/foo-page-1-table-1.csv'.format(date,StateCode),names = ["Details","Numbers"])  

# col_dict = {"Name of District":"District","Cumulative Positive Cases":"Confirmed","Cumulative     Recovered/ Discharged Cases":"Recovered","No. of Deaths":"Deceased"}
# df_districts.rename(columns=col_dict,inplace=True)
# # df_districts.drop(columns=['Sr No','Positive Cases Today','Recovery Rate (%)','No of Active Cases','COVID-19, Vaccination Status  (NHM, Haryana)'],inplace=True)
# # print(df_districts)
# # a=b

In [119]:
df_districts

,Sr No,Name of District,Positive Cases Today,No of Active Cases,Cumulative Positive Cases,Cumulative Recovered/ Discharged Cases,Recovery Rate (%),No. of Deaths,"COVID-19, Vaccination Status (NHM, Haryana)*",Unnamed: 9,Unnamed: 10,Unnamed: 11
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Coverage of Vaccination \non 11-06-2022,NaN,NaN,Cumulative Coverage of \nVaccination
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Dose 1st,Dose 2nd,Precaution \nDose,NaN
2,1 Gurugram,NaN,260.0,961.0,276207.0,274239 [99] ↑,99.29%,1007.0,182,681,4300,5392654
3,2,Faridabad,86.0,307.0,130214.0,129166 [16] ↑,99.20%,741.0,134,428,1473,4059363
4,3 Hisar,NaN,4.0,18.0,62187.0,60994 [4] ↑,98.08%,1175.0,150,313,129,2353935
5,4,Sonipat,1.0,18.0,58744.0,58450 [2] ↑,99.50%,276.0,21,188,207,2293069
6,5,Karnal,2.0,9.0,48274.0,47669,98.75%,596.0,60,370,219,2395597
7,6,Panchkula,30.0,74.0,44455.0,43967 [3] ↑,98.90%,414.0,84,322,666,1128068
8,7,Ambala,4.0,22.0,40836.0,40272,98.62%,542.0,52,142,853,2142048
9,8,Panipat,0.0,9.0,36124.0,35443 [1] ↑,98.11%,672.0,54,251,474,2059042
10,9,Sirsa,0.0,4.0,33419.0,32876,98.38%,539.0,40,217,283,1940585
11,10 Rohtak,NaN,3.0,16.0,32004.0,31434 [1] ↑,98.22%,537.0,74,2276,720,1706453
12,NaN,11 Yamunanagar,0.0,5.0,30699.0,30239,98.50%,455.0,69,944,376,1966240
13,12 Kurukshetra,NaN,1.0,15.0,26878.0,26465 [1] ↑,98.46%,398.0,29,265,272,1559795
14,13 Bhiwani,NaN,0.0,14.0,26554.0,25875,97.44%,665.0,118,595,655,1780825
15,NaN,14 Mahendragarh,0.0,0.0,24754.0,24589,99.33%,165.0,82,275,380,1386467
16,15 Rewari,NaN,2.0,5.0,24662.0,24433 [2] ↑,99.07%,224.0,95,409,1217,1576499
17,16,Jind,3.0,6.0,24370.0,23822 [3] ↑,97.75%,542.0,42,446,255,1720767
18,17,Jhajjar,2.0,8.0,23532.0,23168,98.45%,350.0,28,133,193,1580245
19,18 Fatehabad,NaN,0.0,3.0,20082.0,19581,97.51%,498.0,1,14,19,1193753
20,19 Kaithal,NaN,7.0,17.0,14265.0,13877,97.28%,371.0,23,433,466,1773609
21,20 Palwal,NaN,0.0,1.0,13509.0,13338,98.73%,170.0,31,67,145,1539484
22,NaN,21 Charkhi Dadri,6.0,10.0,7468.0,7313,97.92%,145.0,7,57,641,901683
23,22 Nuh,NaN,0.0,3.0,6122.0,5980,97.68%,139.0,3,17,25,1222173
24,HARYANA,NaN,411.0,1525.0,1005359.0,993190 [132] ↑,98.79%,10621.0,1379,8843,13968,43672354

In [120]:
df_districts['Sr No'] = df_districts['Sr No'] + ' '
df_districts['Name of District'] = df_districts[['Sr No','Name of District']].fillna(' ').sum(axis=1)
df_districts['Name of District'] = df_districts['Name of District'].str.split(' ')
for i in range(0,10):
    for idx in df_districts.index:
        try:
            df_districts['Name of District'][idx].remove('')
        except:
            pass
df_districts['Name of District'] = df_districts["Name of District"].str[-1]

In [125]:
df_districts

,Sr No,Name of District,Positive Cases Today,No of Active Cases,Cumulative Positive Cases,Cumulative Recovered/ Discharged Cases,Recovery Rate (%),No. of Deaths,"COVID-19, Vaccination Status (NHM, Haryana)*",Unnamed: 9,Unnamed: 10,Unnamed: 11
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Coverage of Vaccination \non 11-06-2022,NaN,NaN,Cumulative Coverage of \nVaccination
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Dose 1st,Dose 2nd,Precaution \nDose,NaN
2,1 Gurugram,Gurugram,260.0,961.0,276207.0,274239 [99] ↑,99.29%,1007.0,182,681,4300,5392654
3,2,Faridabad,86.0,307.0,130214.0,129166 [16] ↑,99.20%,741.0,134,428,1473,4059363
4,3 Hisar,Hisar,4.0,18.0,62187.0,60994 [4] ↑,98.08%,1175.0,150,313,129,2353935
5,4,Sonipat,1.0,18.0,58744.0,58450 [2] ↑,99.50%,276.0,21,188,207,2293069
6,5,Karnal,2.0,9.0,48274.0,47669,98.75%,596.0,60,370,219,2395597
7,6,Panchkula,30.0,74.0,44455.0,43967 [3] ↑,98.90%,414.0,84,322,666,1128068
8,7,Ambala,4.0,22.0,40836.0,40272,98.62%,542.0,52,142,853,2142048
9,8,Panipat,0.0,9.0,36124.0,35443 [1] ↑,98.11%,672.0,54,251,474,2059042
10,9,Sirsa,0.0,4.0,33419.0,32876,98.38%,539.0,40,217,283,1940585
11,10 Rohtak,Rohtak,3.0,16.0,32004.0,31434 [1] ↑,98.22%,537.0,74,2276,720,1706453
12,NaN,Yamunanagar,0.0,5.0,30699.0,30239,98.50%,455.0,69,944,376,1966240
13,12 Kurukshetra,Kurukshetra,1.0,15.0,26878.0,26465 [1] ↑,98.46%,398.0,29,265,272,1559795
14,13 Bhiwani,Bhiwani,0.0,14.0,26554.0,25875,97.44%,665.0,118,595,655,1780825
15,NaN,Mahendragarh,0.0,0.0,24754.0,24589,99.33%,165.0,82,275,380,1386467
16,15 Rewari,Rewari,2.0,5.0,24662.0,24433 [2] ↑,99.07%,224.0,95,409,1217,1576499
17,16,Jind,3.0,6.0,24370.0,23822 [3] ↑,97.75%,542.0,42,446,255,1720767
18,17,Jhajjar,2.0,8.0,23532.0,23168,98.45%,350.0,28,133,193,1580245
19,18 Fatehabad,Fatehabad,0.0,3.0,20082.0,19581,97.51%,498.0,1,14,19,1193753
20,19 Kaithal,Kaithal,7.0,17.0,14265.0,13877,97.28%,371.0,23,433,466,1773609
21,20 Palwal,Palwal,0.0,1.0,13509.0,13338,98.73%,170.0,31,67,145,1539484
22,NaN,Dadri,6.0,10.0,7468.0,7313,97.92%,145.0,7,57,641,901683
23,22 Nuh,Nuh,0.0,3.0,6122.0,5980,97.68%,139.0,3,17,25,1222173
24,HARYANA,HARYANA,411.0,1525.0,1005359.0,993190 [132] ↑,98.79%,10621.0,1379,8843,13968,43672354

In [81]:
df_districts["Name of District"].str[-1]

0              NaN
1              NaN
2         Gurugram
3        Faridabad
4            Hisar
5          Sonipat
6           Karnal
7        Panchkula
8           Ambala
9          Panipat
10           Sirsa
11          Rohtak
12     Yamunanagar
13     Kurukshetra
14         Bhiwani
15    Mahendragarh
16          Rewari
17            Jind
18         Jhajjar
19       Fatehabad
20         Kaithal
21          Palwal
22           Dadri
23             Nuh
24         HARYANA
Name: Name of District, dtype: object